export const mockProperties = [
  {
    id: 1,
    title: "Modern 3 Bedroom Apartment",
    location: "Lekki Phase 1, Lagos",
    price: 65000000, // Purchase price
    type: "Apartment",
    beds: 3,
    baths: 2,
    size: 120, // sqm
    image:
      "https://images.unsplash.com/photo-1663021935935-ce2534cc79e3?w=200&dpr=2&crop=entropy&h=150&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    isFeatured: true,
    isPremium: true,
    agent: {
      name: "Adebayo Johnson",
      phone: "+234 812 345 6789",
      email: "adebayo@realestate.ng",
      photo: "https://randomuser.me/api/portraits/men/32.jpg",
      isVerified: true,
    },
    description:
      "Beautiful modern apartment in prime Lekki location with 24/7 security, swimming pool, and gym facilities. Fully furnished with quality finishes.",
    features: [
      "Swimming Pool",
      "24/7 Security",
      "Gym",
      "Parking Space",
      "Fully Furnished",
    ],
  },
  {
    id: 2,
    title: "Spacious 4 Bedroom Duplex",
    location: "Victoria Island, Lagos",
    price: 120000000,
    type: "Duplex",
    beds: 4,
    baths: 4,
    size: 300,
    image:
      "https://images.unsplash.com/photo-1702014860610-06a4c3f83381?w=200&dpr=2&crop=entropy&h=150&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    isFeatured: true,
    isPremium: true,
    agent: {
      name: "Chioma Okonkwo",
      phone: "+234 803 456 7890",
      email: "chioma@realestate.ng",
      photo: "https://randomuser.me/api/portraits/women/44.jpg",
      isVerified: true,
    },
    description:
      "Luxury duplex in the heart of Victoria Island with smart home features, private garden and staff quarters.",
    features: [
      "Smart Home",
      "Private Garden",
      "Staff Quarters",
      "Security",
      "Parking",
    ],
  },
  {
    id: 3,
    title: "5 Bedroom Detached House",
    location: "Ikoyi, Lagos",
    price: 250000000,
    type: "House",
    beds: 5,
    baths: 5,
    size: 450,
    image:
      "https://images.unsplash.com/photo-1702014860012-e0139aae6f69?w=200&dpr=2&crop=entropy&h=150&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    isFeatured: false,
    isPremium: true,
    agent: {
      name: "Emeka Okafor",
      phone: "+234 802 567 8901",
      email: "emeka@realestate.ng",
      photo: "https://randomuser.me/api/portraits/men/22.jpg",
      isVerified: true,
    },
    description:
      "Exclusive detached house in highbrow Ikoyi neighborhood with panoramic views and luxury finishes throughout.",
    features: [
      "Panoramic Views",
      "Home Theater",
      "Swimming Pool",
      "Smart Home",
      "Generator",
    ],
  },
  {
    id: 4,
    title: "2 Bedroom Flat",
    location: "Surulere, Lagos",
    price: 35000000,
    type: "Flat",
    beds: 2,
    baths: 2,
    size: 90,
    image:
      "https://images.unsplash.com/photo-1724862873281-238213626373?w=200&dpr=2&crop=entropy&h=150&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    isFeatured: false,
    isPremium: false,
    agent: {
      name: "Folake Adeleke",
      phone: "+234 815 678 9012",
      email: "folake@realestate.ng",
      photo: "https://randomuser.me/api/portraits/women/33.jpg",
      isVerified: false,
    },
    description:
      "Affordable 2 bedroom flat in central Surulere location, close to amenities and transport links.",
    features: [
      "24/7 Security",
      "Parking",
      "Water Supply",
      "Close to Amenities",
    ],
  },
  {
    id: 5,
    title: "3 Bedroom Terrace",
    location: "GRA, Ibadan",
    price: 45000000,
    type: "Terrace",
    beds: 3,
    baths: 3,
    size: 150,
    image:
      "https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?w=200&dpr=2&crop=entropy&h=150&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    isFeatured: true,
    isPremium: false,
    agent: {
      name: "Yusuf Bello",
      phone: "+234 807 789 0123",
      email: "yusuf@realestate.ng",
      photo: "https://randomuser.me/api/portraits/men/55.jpg",
      isVerified: true,
    },
    description:
      "Well-maintained terrace house in Government Reserved Area (GRA) Ibadan with ample outdoor space.",
    features: [
      "Ample Outdoor Space",
      "Security",
      "Quiet Neighborhood",
      "Parking",
    ],
  },
  {
    id: 6,
    title: "4 Bedroom Semi-Detached",
    location: "Wuse 2, Abuja",
    price: 85000000,
    type: "House",
    beds: 4,
    baths: 4,
    size: 280,
    image:
      "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=200&dpr=2&crop=entropy&h=150&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    isFeatured: false,
    isPremium: true,
    agent: {
      name: "Amina Mohammed",
      phone: "+234 809 890 1234",
      email: "amina@realestate.ng",
      photo: "https://randomuser.me/api/portraits/women/66.jpg",
      isVerified: true,
    },
    description:
      "Elegant semi-detached house in prime Wuse 2 location with modern amenities and security.",
    features: [
      "Modern Amenities",
      "Security",
      "Generator",
      "Parking",
      "Garden",
    ],
  },
];